--[[

Differ has made use of several packages and tools made by other members of the Roblox community.
The tools that were used in the making of Differ are as follows:

- boatbomber's Highlighter
	- Used for highlighting the code when previewing the differences of scripts
	- https://github.com/boatbomber/Highlighter
	
- cxmeel's DumpParser
	- Used for getting instance properties
	- The version is slightly forked, as the `FetchVersionHashWithFallback` is modified to be more reliable by adding an extra check
	- https://github.com/cxmeel/dump-parser
	
- PepeElToro41's UILabs
	- The UI of this plugin is heavily inspired by UI labs as I found it very nice to use and look at
	- UILabs was also used to make the creation of the UI easier
	- https://github.com/PepeElToro41/ui-labs

Big thank you to all of the above :)

]]